### ISSUE TITLE
Compatibilidade Moderninha Smarth

### ISSUE THREAD

**Issue by FabioRoesler** [pagseguro/plugpag#66]
Olá a todos.
Estou tentando fazer a integração Windows C# em uma moderninha Smarth, porem retorna o codigo 2004 (TimeOut).
Agora estou na duvida se esta maquininha é compatível com a integração. Se for o caso vou trocar por uma moderninha PRO 2. Creio que esta é 100% compatível. Alguem pode me dar uma luz?

**Comment by angelopedroso** [comment]
Nenhuma smart é compátivel, eu também estou integrando os terminais da pagseguro, se quiser trocar contato pra nós se ajudarmos, só avisar.

**Comment by FabioRoesler** [comment]
Obrigado pelo comentário. Em paralelo comprei uma Moderninha Pro, e funcionou perfeitamente.
